name: Suggestion
description: Suggest a new feature or change for Schizoid.
title: '[Suggestion] '
labels: enhancement
body:
  - type: textarea
    id: description
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature/change is.
    validations:
      required: true
  - type: checkboxes
    id: prerequisites
    attributes:
      label: Before submitting a suggestion
      options:
        - label: |
            This feature doesn't already exist.
            (I have checked the source on the **latest build**)
          required: true
        - label: |
            This wasn't already suggested.
            (I have checked every suggestion on github)
          required: true
